/**
 * AutoFlow AI — Cloud Deployment Packager Service
 * Generates production-ready Dockerfile, FastAPI microservice, requirements.txt,
 * docker-compose.yml, and deployment documentation for LangGraph pipelines.
 */

import JSZip from 'jszip';
import { generatePythonLangGraph } from '../utils/codeGenerator.js';

/**
 * Generates the full file suite for production container deployment
 */
export function generateCloudDeploymentPackage(workflowName, nodes, connections) {
  const safeName = (workflowName || 'autoflow-agent')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-');

  const pythonLangGraphCode = generatePythonLangGraph(workflowName, nodes, connections);

  // 1. FastAPI Microservice main.py
  const mainPy = `"""
AutoFlow AI — Production Microservice
Generated by AutoFlow AI Studio
Workflow: ${workflowName}
"""

import os
import json
import logging
from typing import Dict, Any, Optional
from fastapi import FastAPI, HTTPException, Request, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("autoflow-service")

# --- Exported LangGraph Pipeline Core ---
${pythonLangGraphCode}

# Compile executable graph
app_graph = workflow.compile()

# --- FastAPI Server Definition ---
app = FastAPI(
    title="AutoFlow AI Microservice - ${workflowName}",
    description="Production HTTP microservice running compiled LangGraph agentic pipeline.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class PipelineRunRequest(BaseModel):
    payload: Dict[str, Any] = Field(default_factory=dict, description="Inbound payload dictionary")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Execution metadata")

class PipelineRunResponse(BaseModel):
    success: bool
    status: str
    output: Dict[str, Any]

@app.get("/health", tags=["Monitoring"])
async def health_check():
    return {
        "status": "HEALTHY",
        "service": "${safeName}",
        "version": "1.0.0",
        "node_count": ${nodes.length},
        "connection_count": ${connections.length}
    }

@app.post("/api/v1/run", response_model=PipelineRunResponse, tags=["Agent Execution"])
async def run_pipeline(request: PipelineRunRequest):
    try:
        logger.info("Received execution request for pipeline: ${workflowName}")
        initial_state = {
            "input_payload": request.payload,
            "current_context": json.dumps(request.payload),
            "intermediate_steps": [],
            "final_output": {},
            "execution_status": "RUNNING"
        }
        
        # Execute LangGraph
        result = app_graph.invoke(initial_state)
        
        return PipelineRunResponse(
            success=True,
            status=result.get("execution_status", "COMPLETED"),
            output=result.get("final_output", {})
        )
    except Exception as e:
        logger.error(f"Pipeline execution error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/v1/webhook", tags=["Webhooks"])
async def handle_webhook(request: Request, background_tasks: BackgroundTasks):
    try:
        body = await request.json()
        logger.info("Webhook event received. Queuing execution...")
        # Dispatch background task
        background_tasks.add_task(
            app_graph.invoke,
            {
                "input_payload": body,
                "current_context": json.dumps(body),
                "intermediate_steps": [],
                "final_output": {},
                "execution_status": "QUEUED"
            }
        )
        return {"status": "ACCEPTED", "message": "Webhook payload received and queued."}
    except Exception as e:
        logger.error(f"Webhook processing error: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Invalid webhook body: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
`;

  // 2. Production Dockerfile
  const dockerfile = `# AutoFlow AI — Production Container Image
FROM python:3.11-slim as base

# Set working directory & environment variables
WORKDIR /app
ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PIP_NO_CACHE_DIR=1

# Install security updates & curl for healthcheck
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Create non-root application user for container security
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

# Copy application source code
COPY . .

# Expose HTTP port
EXPOSE 8000

# Container Healthcheck
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:8000/health || exit 1

# Launch FastAPI ASGI server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;

  // 3. requirements.txt
  const requirementsTxt = `# Production Dependencies for ${workflowName}
fastapi>=0.110.0
uvicorn[standard]>=0.28.0
pydantic>=2.6.0
python-dotenv>=1.0.0
langgraph>=0.2.0
langchain-core>=0.2.0
langchain-anthropic>=0.1.0
langchain-google-genai>=1.0.0
pika>=1.3.2
httpx>=0.27.0
`;

  // 4. docker-compose.yml
  const dockerComposeYml = `version: '3.8'

services:
  ${safeName}:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${safeName}-service
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=\${GEMINI_API_KEY}
      - OPENAI_API_KEY=\${OPENAI_API_KEY}
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${safeName}-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
`;

  // 5. .env.example
  const envExample = `# API Keys for Multi-Agent LLM Providers
ANTHROPIC_API_KEY=sk-ant-api03-...
GEMINI_API_KEY=AIzaSy...
OPENAI_API_KEY=sk-proj-...
GROQ_API_KEY=gsk_...

# AMQP Broker Credentials
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest
`;

  // 6. README.md Deployment Guide
  const readmeMd = `# 🚀 ${workflowName} — Cloud Deployment Package

Exported from **AutoFlow AI Studio**.
This package contains a production-ready **FastAPI** service running a compiled **LangGraph** pipeline.

---

## ⚡ Quickstart (Local Docker)

\`\`\`bash
# 1. Copy environment variables
cp .env.example .env
# Fill in your ANTHROPIC_API_KEY or GEMINI_API_KEY in .env

# 2. Build & Launch via Docker Compose
docker compose up --build -d

# 3. Verify Health Check
curl http://localhost:8000/health
\`\`\`

---

## 🌐 API Endpoints

### 1. Execute Pipeline (\`POST /api/v1/run\`)
\`\`\`bash
curl -X POST http://localhost:8000/api/v1/run \\
  -H "Content-Type: application/json" \\
  -d '{"payload": {"user_query": "Reconcile payment ledger"}}'
\`\`\`

### 2. Inbound Webhook (\`POST /api/v1/webhook\`)
Accepts external webhooks (Stripe, Zendesk, GitHub) and executes in background queue.

---

## ☁️ Cloud Deployment Commands

### Google Cloud Run:
\`\`\`bash
gcloud run deploy ${safeName} \\
  --source . \\
  --region us-central1 \\
  --allow-unauthenticated \\
  --set-env-vars ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
\`\`\`

### Fly.io:
\`\`\`bash
fly launch --name ${safeName}
fly secrets set ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
fly deploy
\`\`\`

### AWS ECS / App Runner:
Build the Docker image and push to AWS ECR:
\`\`\`bash
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin \${AWS_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com
docker build -t ${safeName} .
docker tag ${safeName}:latest \${AWS_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/${safeName}:latest
docker push \${AWS_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/${safeName}:latest
\`\`\`
`;

  return {
    packageName: safeName,
    files: {
      'main.py': mainPy,
      'Dockerfile': dockerfile,
      'requirements.txt': requirementsTxt,
      'docker-compose.yml': dockerComposeYml,
      '.env.example': envExample,
      'README.md': readmeMd
    }
  };
}

/**
 * Downloads the full file suite as a single .zip archive
 */
export async function downloadCloudDeploymentZip(packageName, files) {
  const zip = new JSZip();

  Object.entries(files).forEach(([filename, content]) => {
    zip.file(filename, content);
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${packageName}-cloud-package.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
