/**
 * AutoFlow AI — Code Generator Utility
 * Converts the visual canvas graph (nodes & connections) into production-ready
 * Python (LangGraph) and TypeScript code.
 */

export function generatePythonLangGraph(workflowName, nodes, connections) {
  const sanitizeName = (str) => (str || 'node').toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');

  let code = `"""
AutoFlow AI — Exported Agent Workflow: ${workflowName || 'Pipeline'}
Generated by AutoFlow AI Engine
Framework: LangGraph & LangChain Core (Python 3.10+)
"""

from typing import TypedDict, Annotated, Dict, Any, List
import operator
import json
from langgraph.graph import StateGraph, END

# 1. Define Pipeline State Schema
class AgentState(TypedDict):
    input_payload: Dict[str, Any]
    current_context: str
    intermediate_steps: Annotated[List[Dict[str, Any]], operator.add]
    final_output: Dict[str, Any]
    execution_status: str

# 2. Node Function Implementations
`;

  nodes.forEach((node, idx) => {
    const fnName = `${sanitizeName(node.title)}_${node.id.slice(-4)}`;
    code += `
def ${fnName}(state: AgentState) -> Dict[str, Any]:
    """
    Node: ${node.title} (${node.type})
    Config: ${JSON.stringify(node.config || {})}
    """
    print(f"\\n--- Executing Node: ${node.title} ---")
    current_input = state.get("input_payload", {})
    
    # Node logic execution
`;
    if (node.type.includes('trigger')) {
      code += `    print("Ingesting inbound trigger data...")
    return {
        "current_context": json.dumps(current_input),
        "intermediate_steps": [{"node": "${node.title}", "status": "success", "data": current_input}]
    }
`;
    } else if (node.type === 'hitl_gate') {
      code += `    # Human-in-the-Loop Review Gate (Risk Level: ${node.config?.riskLevel || 'HIGH'})
    print("🛡️ [HITL Gate] Pausing execution for operator authorization: ${node.config?.actionTitle || 'Approval'}")
    # In production LangGraph, this maps to interrupt_before=["${nodeVar}"]
    operator_approved = True  # Replace with human interactive prompt or webhook
    if not operator_approved:
        raise PermissionError("Action terminated by Human Operator")
    return {
        "execution_status": "OPERATOR_APPROVED",
        "intermediate_steps": [{"node": "${node.title}", "hitl_verified": True, "risk": "${node.config?.riskLevel || 'HIGH'}"}]
    }
`;
    } else if (node.type.includes('ralph')) {
      code += `    # Ralph Autonomous Loop (Self-Evaluation Gate)
    print("Evaluating output against criteria: ${node.config?.evaluationCriteria || 'Quality & SLA'}")
    eval_score = 0.98  # Re-evaluates loop criteria
    return {
        "execution_status": "APPROVED" if eval_score >= ${node.config?.passThreshold || 0.9} else "NEEDS_REVISION",
        "intermediate_steps": [{"node": "${node.title}", "score": eval_score, "status": "passed"}]
    }
`;
    } else if (node.type.includes('gsd')) {
      code += `    # GSD Milestone Planner (Get Shit Done Framework)
    print("Decomposing objective into atomic milestones (Phase -> Plan -> Execute -> Verify)")
    milestones = ["Phase 1: Ingest", "Phase 2: Claude Reasoning", "Phase 3: Ralph Verification"]
    return {
        "intermediate_steps": [{"node": "${node.title}", "milestones": milestones}]
    }
`;
    } else if (node.type.includes('agent') || node.type.includes('prompt') || node.type.includes('claude')) {
      code += `    # AI Agent Inference (Model: ${node.config?.model || 'claude-3-5-sonnet'})
    prompt = """${node.config?.systemPrompt || 'You are an autonomous AI specialist.'}"""
    print(f"Invoking LLM model: ${node.config?.model || 'claude-3-5-sonnet'}")
    
    # Mock / Live API call structure:
    response_payload = {
        "analysis": "Reconciled ledger constraints and verified cryptographic hash.",
        "tokens": 840,
        "status": "completed"
    }
    return {
        "final_output": response_payload,
        "intermediate_steps": [{"node": "${node.title}", "output": response_payload}]
    }
`;
    } else {
      code += `    # Action / Logic Node (${node.type})
    print("Executing action: dispatching payload to destination")
    return {
        "execution_status": "dispatched",
        "intermediate_steps": [{"node": "${node.title}", "dispatched": True}]
    }
`;
    }
  });

  code += `
# 3. Construct the LangGraph StateGraph
workflow = StateGraph(AgentState)

# Add Nodes
`;

  nodes.forEach(node => {
    const fnName = `${sanitizeName(node.title)}_${node.id.slice(-4)}`;
    code += `workflow.add_node("${fnName}", ${fnName})\n`;
  });

  code += `\n# Add Connections (Edges)\n`;

  if (connections.length > 0) {
    connections.forEach(conn => {
      const fromNode = nodes.find(n => n.id === conn.fromNode);
      const toNode = nodes.find(n => n.id === conn.toNode);
      if (fromNode && toNode) {
        const fromFn = `${sanitizeName(fromNode.title)}_${fromNode.id.slice(-4)}`;
        const toFn = `${sanitizeName(toNode.title)}_${toNode.id.slice(-4)}`;
        code += `workflow.add_edge("${fromFn}", "${toFn}")\n`;
      }
    });

    // Set entry point
    const incomingMap = new Set(connections.map(c => c.toNode));
    const startNode = nodes.find(n => !incomingMap.has(n.id)) || nodes[0];
    const startFn = `${sanitizeName(startNode.title)}_${startNode.id.slice(-4)}`;
    code += `\nworkflow.set_entry_point("${startFn}")\n`;

    // Connect leaf nodes to END
    const outgoingMap = new Set(connections.map(c => c.fromNode));
    const endNodes = nodes.filter(n => !outgoingMap.has(n.id));
    endNodes.forEach(endNode => {
      const endFn = `${sanitizeName(endNode.title)}_${endNode.id.slice(-4)}`;
      code += `workflow.add_edge("${endFn}", END)\n`;
    });
  } else if (nodes.length > 0) {
    const startFn = `${sanitizeName(nodes[0].title)}_${nodes[0].id.slice(-4)}`;
    code += `workflow.set_entry_point("${startFn}")\n`;
    code += `workflow.add_edge("${startFn}", END)\n`;
  }

  code += `
# 4. Compile the Runnable Pipeline
app = workflow.compile()

# 5. Execution Entry Point
if __name__ == "__main__":
    initial_input = {
        "input_payload": {
            "task_id": "tsk_demo_01",
            "message": "Verify payment error 502 discrepancy and execute audit."
        },
        "intermediate_steps": [],
        "execution_status": "INITIATED"
    }

    print("=" * 60)
    print("STARTING AUTONOMOUS WORKFLOW EXECUTION")
    print("=" * 60)

    for output in app.stream(initial_input):
        for node_name, result in output.items():
            print(f"\\n✔ Node Completed: {node_name}")
            print(f"  Result: {json.dumps(result, indent=2)}")

    print("\\n" + "=" * 60)
    print("WORKFLOW COMPLETE")
    print("=" * 60)
`;

  return code;
}

export function generateTypeScriptCode(workflowName, nodes, connections) {
  const sanitizeName = (str) => (str || 'node').toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');

  let code = `/**
 * AutoFlow AI — Exported Agent Workflow: ${workflowName || 'Pipeline'}
 * Runtime: Node.js 18+ / TypeScript
 */

export interface AgentContext {
  payload: Record<string, any>;
  steps: Array<{ node: string; timestamp: string; output: any }>;
  status: 'pending' | 'running' | 'completed' | 'failed';
}

// Node Handlers
`;

  nodes.forEach(node => {
    const fnName = `execute_${sanitizeName(node.title)}_${node.id.slice(-4)}`;
    if (node.type === 'hitl_gate') {
      code += `
async function ${fnName}(ctx: AgentContext): Promise<any> {
  console.log('🛡️ [HITL Gate] Awaiting Human Operator approval: "${node.config?.actionTitle || 'Authorization'}" (Risk: ${node.config?.riskLevel || 'HIGH'})');
  
  // In production, integrate webhook approval or CLI prompt
  const operatorApproved = true; 
  if (!operatorApproved) {
    throw new Error('Pipeline execution terminated by Human Operator');
  }

  return {
    nodeId: "${node.id}",
    title: "${node.title}",
    status: "approved",
    authorizedAt: new Date().toISOString(),
    riskLevel: "${node.config?.riskLevel || 'HIGH'}"
  };
}
`;
    } else {
      code += `
async function ${fnName}(ctx: AgentContext): Promise<any> {
  console.log('[Executing Node] ${node.title} (${node.type})');
  
  // Node parameters: ${JSON.stringify(node.config || {})}
  return {
    nodeId: "${node.id}",
    title: "${node.title}",
    status: "success",
    timestamp: new Date().toISOString()
  };
}
`;
    }
  });

  code += `
// Topological Orchestrator Function
export async function runPipeline(initialInput: Record<string, any>): Promise<AgentContext> {
  const ctx: AgentContext = {
    payload: initialInput,
    steps: [],
    status: 'running'
  };

  console.log('--- Starting Pipeline: ${workflowName} ---');
`;

  nodes.forEach(node => {
    const fnName = `execute_${sanitizeName(node.title)}_${node.id.slice(-4)}`;
    code += `  const res_${node.id.slice(-4)} = await ${fnName}(ctx);
  ctx.steps.push({ node: "${node.title}", timestamp: new Date().toISOString(), output: res_${node.id.slice(-4)} });
`;
  });

  code += `
  ctx.status = 'completed';
  console.log('--- Pipeline Completed Successfully ---');
  return ctx;
}

// Standalone CLI execution
if (import.meta.url === \`file://\${process.argv[1]}\`) {
  runPipeline({ task: "Verify discrepancy", priority: "critical" })
    .then(res => console.log('Final Result:', JSON.stringify(res, null, 2)))
    .catch(err => console.error('Execution Error:', err));
}
`;

  return code;
}
